### ISSUE TITLE
Add const struct tag reflection

### ISSUE THREAD

**Issue by friedemannf** [swaggest/jsonschema-go#27]
I've noticed that the `const` keyword is missing from the accepted list of tags and therefore something like this doesn't result in the `Schema.Const` being set:
```
Method string `json:"method" const:"authenticate"`
```
The const keyword has been added in draft 6:
https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.3

Would it be possible to add this or would you be open in accepting a PR? I believe this could be handled quite similarly to the `default` keyword.

**Comment by vearutop** [comment]
Thank you for raising this issue (and sorry for late reply), fixed by @ghughes in `v0.3.25`.
