### ISSUE TITLE
Implementing TextMarshaler overrides my Schema

### ISSUE THREAD

**Issue by uberbrodt** [swaggest/jsonschema-go#64]
Hi, I noticed that when I implement TextMarshaler on a type, the schema that I set through a Preparer interface is ignored. Looks like it gets picked up by `isWellKnownType` in `reflect.go` before `PrepareJSONSchema` is called.

I'd like some way similar to what was done here, https://github.com/swaggest/jsonschema-go/pull/62 but to make sure it's type is not overridden because it implements TextMarshaler.

**Comment by vearutop** [comment]
You're right, `TextMarshaler` is a fair indicator to add type string, but it definitely should not prevent further processing.
